spring:
  profile.active: test
  datasource:
    url: jdbc:mysql://localhost/vollmed_api_test?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

  ##si quisieramos usar la bade de datos en memoria H2 tendriamos que habiliar las lineas de abajo y
  ##anular la anotacion @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE) en la clase que se haya utilizado

#  spring.datasource.url =jdbc:h2:mem:testdb
#  spring.datasource.driverClassName=org.h2.Driver
#  spring.datasource.username=sa
#  spring.datasource.password=password
#  spring.jpa.database-platform=org.hibernate.dialect.H2Dialect